#include <iostream>
#include "Assembler.h"
#include "VirtualMachine.h"
#include <fstream>
#include <vector>
#include <cstdint>
using namespace std;

void writeBytecodeToFile(const std::vector<int32_t>& bytecode, const std::string& filename) {
    std::ofstream out(filename, std::ios::binary);
    if (!out) {
        std::cerr << "Cannot write bytecode file\n";
        exit(1);
    }
    out.write(reinterpret_cast<const char*>(bytecode.data()),
              bytecode.size() * sizeof(int32_t));
    out.close();
}

std::vector<int32_t> loadBytecodeFromFile(const std::string& filename) {
    std::ifstream in(filename, std::ios::binary);
    if (!in) {
        std::cerr << "Cannot open bytecode file\n";
        exit(1);
    }

    in.seekg(0, std::ios::end);
    size_t size = in.tellg();
    in.seekg(0, std::ios::beg);

    if (size % sizeof(int32_t) != 0) {
        std::cerr << "Invalid bytecode file format\n";
        exit(1);
    }

    std::vector<int32_t> bytecode(size / sizeof(int32_t));
    in.read(reinterpret_cast<char*>(bytecode.data()), size);
    in.close();

    return bytecode;
}

string replaceExtension(const string& filename,
                        const string& newExt) {
    size_t pos = filename.find_last_of('.');
    if (pos == string::npos) {
        return filename + newExt;
    }
    return filename.substr(0, pos) + newExt;
}

void dumpBytecodeHex(const std::vector<int32_t>& bytecode) {
    std::cout << "\n=== Generated Bytecode (word-based, hex) ===\n";
    for (size_t i = 0; i < bytecode.size(); i++) {
        printf("%04zu : 0x%08X\n", i, (uint32_t)bytecode[i]);
    }
}

int main(int argc, char* argv[]) {
    if (argc < 2) {
        cout << "Usage:\n";
        cout << "  ./vm --assemble program.asm\n";
        cout << "  ./vm program.byc\n";
        return 1;
    }

    string arg1 = argv[1];
    
    if (arg1 == "--assemble") {
        if (argc < 3) {
        cerr << "Usage: ./vm --assemble program.asm\n";
        return 1;
        }
        string asmFile = argv[2];
        auto bytecode = assemble(asmFile);

        dumpBytecodeHex(bytecode);        
        string outFile = replaceExtension(asmFile, ".byc");
        writeBytecodeToFile(bytecode, outFile);


        return 0;
    }

    auto bytecode = loadBytecodeFromFile(arg1);
    VM vm(bytecode);
    vm.run();
}
